# Generated by Django 5.0.1 on 2024-02-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_question_question_image_choice_explanation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='explanation',
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
