# Generated by Django 5.0.1 on 2024-02-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_choice',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_choices',
            field=models.ManyToManyField(related_name='correct_for', to='quiz.choice'),
        ),
    ]
