# Generated by Django 5.0.1 on 2024-02-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_question_correct_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_correct',
        ),
    ]
