# Generated by Django 5.0.1 on 2024-02-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_choice_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
